version: "3.9"

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  flask:
    build:
      context: .
      dockerfile: Dockerfile.flask
    container_name: flask
    ports:
      - "5000:5000"
    volumes:
      - ./flask/uploads:/app/uploads
      - ./flask/results:/app/results
    depends_on:
      - redis

  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: node
    ports:
      - "3000:3000"
    depends_on:
      - redis
    volumes:
      - ./flask/results:/app/flask/results
