FROM python:3.10-slim

WORKDIR /app

# Install dependencies
COPY flask/requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy code
COPY flask/ .

EXPOSE 5000

CMD ["python", "app.py"]
