FROM python:3.12-slim


WORKDIR /app


RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    python3-dev \
    curl \
    sqlite3 \
    && rm -rf /var/lib/apt/lists/*

COPY flask/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt


RUN mkdir -p /app/database


COPY flask/ ./


EXPOSE 5000


CMD ["python", "app.py"]