FROM node:18

WORKDIR /app

# Install dependencies
COPY node/package.json node/package-lock.json* ./
RUN npm install

# Copy code
COPY node/ .

# Install OpenCV deps and build C++ processor
RUN apt-get update && apt-get install -y build-essential cmake pkg-config libopencv-dev

COPY cpp/ /app/cpp/
WORKDIR /app/cpp
RUN mkdir build && cd build && cmake .. && cmake --build . --config Release

WORKDIR /app

EXPOSE 3000
