global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'flask'
    static_configs:
      - targets: ['host.docker.internal:5001']  # Use host machine ports
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'node'
    static_configs:
      - targets: ['host.docker.internal:3001']  # Use host machine ports
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s